// Candidate employers hiring in India. scripts/probe-companies.ts verifies each against the live careers systems;
// only boards that answer with India-relevant jobs are written to server/jobs/seed/companies.json.

/** Name → industry. The probe tries slug variants of the name on Greenhouse, Lever, Ashby, Recruitee and Workable. */
export const GUESS: Record<string, string> = {
  // Indian startups & product companies
  Razorpay: "fintech", PhonePe: "fintech", Swiggy: "consumer", Zomato: "consumer", Zepto: "consumer", Blinkit: "consumer", Meesho: "ecommerce",
  CRED: "fintech", Groww: "fintech", Zerodha: "fintech", Upstox: "fintech", Paytm: "fintech", Policybazaar: "insurance", Nykaa: "ecommerce",
  Lenskart: "retail", "Urban Company": "consumer", Dunzo: "consumer", Rapido: "mobility", Ola: "mobility", "Ola Electric": "automotive",
  "Ather Energy": "automotive", boAt: "consumer", Mamaearth: "consumer", Licious: "consumer", FreshToHome: "consumer", BigBasket: "ecommerce",
  Flipkart: "ecommerce", Myntra: "ecommerce", ClearTax: "fintech", Khatabook: "fintech", OkCredit: "fintech", Jupiter: "fintech",
  Slice: "fintech", Navi: "fintech", Acko: "insurance", "Digit Insurance": "insurance", Zeta: "fintech", Juspay: "fintech",
  Cashfree: "fintech", "Pine Labs": "fintech", BharatPe: "fintech", MobiKwik: "fintech", Instamojo: "fintech", Chargebee: "saas", Freshworks: "saas",
  Postman: "saas", BrowserStack: "saas", Hasura: "saas", Druva: "saas", Sprinklr: "saas", Innovaccer: "healthtech", Practo: "healthtech",
  PharmEasy: "healthtech", "Tata 1mg": "healthtech", "Cult.fit": "health", HealthifyMe: "healthtech", Unacademy: "edtech", BYJUS: "edtech",
  upGrad: "edtech", Vedantu: "edtech", "Physics Wallah": "edtech", Scaler: "edtech", Simplilearn: "edtech", Eruditus: "edtech", Classplus: "edtech",
  LeadSquared: "saas", Whatfix: "saas", MindTickle: "saas", Keka: "saas", Zluri: "saas", Rocketlane: "saas", Atlan: "saas", Gupshup: "saas",
  "Yellow.ai": "saas", Haptik: "saas", Uniphore: "saas", "Observe.AI": "saas", ShareChat: "media", Dailyhunt: "media", Inshorts: "media",
  "Pocket FM": "media", "Kuku FM": "media", Dream11: "gaming", MPL: "gaming", Games24x7: "gaming", WinZO: "gaming", Nazara: "gaming",
  Cars24: "automotive", Spinny: "automotive", CarDekho: "automotive", OYO: "travel", MakeMyTrip: "travel", ixigo: "travel", Cleartrip: "travel",
  Delhivery: "logistics", Shadowfax: "logistics", Porter: "logistics", BlackBuck: "logistics", Shiprocket: "logistics", Xpressbees: "logistics",
  Udaan: "ecommerce", Jumbotail: "ecommerce", Ninjacart: "agritech", DeHaat: "agritech", Zetwerk: "manufacturing", OfBusiness: "b2b",
  Moglix: "b2b", Bizongo: "b2b", Lendingkart: "fintech", KreditBee: "fintech", "Money View": "fintech", Fibe: "fintech",
  INDmoney: "fintech", smallcase: "fintech", CoinSwitch: "fintech", CoinDCX: "fintech", Polygon: "web3", Turing: "staffing", HackerRank: "saas",
  HackerEarth: "saas", Testbook: "edtech", Apna: "hr", WorkIndia: "hr", Housing: "realestate", NoBroker: "realestate", "Square Yards": "realestate",
  Livspace: "realestate", HomeLane: "realestate", Pepperfry: "ecommerce", Purplle: "ecommerce", Bewakoof: "ecommerce", Snitch: "ecommerce",
  InMobi: "adtech", Glance: "adtech", CleverTap: "saas", MoEngage: "saas", WebEngage: "saas", Exotel: "saas", Ozonetel: "saas", Kapture: "saas",
  Tekion: "saas", HighRadius: "saas", Icertis: "saas", Darwinbox: "saas", Perfios: "fintech", Signzy: "fintech", Setu: "fintech", M2P: "fintech",
  Rupeek: "fintech", Stashfin: "fintech", Paysense: "fintech", Kissht: "fintech",
  Zolve: "fintech", Niyo: "fintech", Sarvam: "ai", "Krutrim": "ai", Composio: "ai",
  // Global companies with large India teams
  Atlassian: "saas", Rubrik: "saas", Confluent: "saas", ThoughtSpot: "saas", Nutanix: "saas", Zscaler: "security", Twilio: "saas", Okta: "security",
  MongoDB: "saas", Elastic: "saas", Datadog: "saas", GitLab: "saas", HashiCorp: "saas", Cloudflare: "security", Stripe: "fintech", Databricks: "data",
  Snowflake: "data", Coinbase: "fintech", Robinhood: "fintech", DoorDash: "consumer", Instacart: "consumer", Pinterest: "media", Reddit: "media",
  Discord: "media", Figma: "saas", Canva: "saas", Notion: "saas", Airtable: "saas", Asana: "saas", Dropbox: "saas", Box: "saas", HubSpot: "saas",
  Intercom: "saas", Miro: "saas", Samsara: "saas", Toast: "saas", Rippling: "saas", Gusto: "saas", Brex: "fintech", Plaid: "fintech", Affirm: "fintech",
  Marqeta: "fintech", Carta: "fintech", Benchling: "saas", Harness: "saas", "Sumo Logic": "saas", "New Relic": "saas", Grab: "consumer", Gojek: "consumer",
  Uber: "mobility", Airbnb: "travel", Expedia: "travel", Agoda: "travel", Zendesk: "saas", Freshdesk: "saas", Wise: "fintech",
  Revolut: "fintech", Deel: "hr", "Oyster HR": "hr", Zapier: "saas", Ramp: "fintech", Cohere: "ai", OpenAI: "ai", Anthropic: "ai",
  Glean: "ai", "Scale AI": "ai", Vercel: "saas", Retool: "saas", Linear: "saas", Supabase: "saas", PostHog: "saas", Sentry: "saas", Grafana: "saas",
  "Grafana Labs": "saas", Kong: "saas", Temporal: "saas", Redis: "data", Couchbase: "data", Yugabyte: "data", "Cockroach Labs": "data", SingleStore: "data",
  Fivetran: "data", dbt: "data", "dbt Labs": "data", Airbyte: "data", Hevo: "data", Algolia: "saas", Contentful: "saas", Contentstack: "saas",
  LambdaTest: "saas", Mixpanel: "saas", Amplitude: "saas", Optimizely: "saas",
  Freshtohome: "consumer", Wingify: "saas", Paxos: "fintech", Chainalysis: "fintech", Alchemy: "web3", Coinshift: "web3", Biconomy: "web3",
  Increff: "saas", Capillary: "saas", Unbxd: "saas", Vymo: "saas", Sigmoid: "data", Tredence: "data", "Fractal": "data", "Mu Sigma": "data",
  LatentView: "data", "Tiger Analytics": "data", Quantiphi: "data", Searce: "cloud", CloudKeeper: "cloud", Nagarro: "it_services", Thoughtworks: "it_services",
  "Publicis Sapient": "it_services", EPAM: "it_services", Globant: "it_services", Endava: "it_services", Accolite: "it_services", "Sigma Solve": "it_services",
  // More Indian startups, scale-ups and mid-size product companies
  Unacademy: "edtech", "Physics Wallah": "edtech", upGrad: "edtech", Vedantu: "edtech", Scaler: "edtech", "Great Learning": "edtech", Eruditus: "edtech",
  Emeritus: "edtech", Simplilearn: "edtech", Classplus: "edtech", Teachmint: "edtech", LEAD: "edtech", Byjus: "edtech", Cuemath: "edtech", Toppr: "edtech",
  PharmEasy: "healthcare", "Tata 1mg": "healthcare", Practo: "healthcare", "Cult.fit": "healthcare", Curefit: "healthcare", HealthifyMe: "healthcare",
  Pristyn: "healthcare", "Pristyn Care": "healthcare", Medanta: "healthcare", Qure: "healthcare", "Qure.ai": "healthcare", Innovaccer2: "healthcare",
  MediBuddy: "healthcare", Truemeds: "healthcare", Even: "healthcare", Plum: "insurance", Loop: "insurance", "Onsurity": "insurance", InsuranceDekho: "insurance",
  Turtlemint: "insurance", RenewBuy: "insurance", "Go Digit": "insurance", Zype: "fintech", Fampay: "fintech", Uni: "fintech", OneCard: "fintech",
  Scapia: "fintech", Kiwi: "fintech", Rupifi: "fintech", Vayana: "fintech", Yubi: "fintech", CredAvenue: "fintech", "Credit Saison": "fintech",
  Aspora: "fintech", Dezerv: "fintech", Jar: "fintech", Kuvera: "fintech", ET_Money: "fintech", Angel: "fintech", "Angel One": "fintech",
  Dhan: "fintech", Sensibull: "fintech", Tartan: "fintech", Decentro: "fintech", Razorpayx: "fintech", Open: "fintech", Paytail: "fintech",
  Leap: "edtech", "Leap Finance": "fintech", "LeapScholar": "edtech", Yellow: "ai", "Yellow.ai": "ai", Haptik: "ai", Uniphore: "ai", Observe: "ai",
  "Observe.AI": "ai", Gupshup: "saas", Verloop: "ai", Rocketlane: "saas", Zluri: "saas", Spotdraft: "saas", Atlan: "data", Whatfix: "saas",
  Mindtickle: "saas", Leadsquared: "saas", LeadSquared: "saas", Zoho: "saas", Kissflow: "saas", Chargebee2: "saas", Facilio: "saas", Everstage: "saas",
  Hevodata: "data", "Hevo Data": "data", Airmeet: "saas", Hubilo: "saas", Zenoti: "saas", "Park+": "consumer", Parkplus: "consumer", Ultrahuman: "consumer",
  Noise: "consumer", "Sugar Cosmetics": "consumer", Wakefit: "consumer", "The Souled Store": "ecommerce", FirstCry: "ecommerce", Tata: "conglomerate",
  "Tata CLiQ": "ecommerce", JioMart: "ecommerce", Ajio: "ecommerce", Nobroker2: "realestate", MagicBricks: "realestate", "99acres": "realestate",
  Info_Edge: "internet", Naukri: "internet", Shaadi: "internet", ShareChat: "media", Moj: "media", Dailyhunt: "media", VerSe: "media", Pocket_FM: "media",
  "Pocket FM": "media", KukuFM: "media", "Kuku FM": "media", Pratilipi: "media", InShorts: "media", Josh: "media", "Games24x7": "gaming", Dream11: "gaming",
  "Dream Sports": "gaming", MPL: "gaming", "Mobile Premier League": "gaming", Nazara: "gaming", WinZO: "gaming", Zupee: "gaming", Junglee: "gaming",
  "Junglee Games": "gaming", Loco: "gaming", Rooter: "gaming", Zeta2: "fintech", "Ather": "automotive", Euler: "automotive", "Euler Motors": "automotive",
  Yulu: "mobility", Bounce: "mobility", Vogo: "mobility", Blusmart: "mobility", BluSmart: "mobility", Battery_Smart: "energy", "Battery Smart": "energy",
  Log9: "energy", ReNew: "energy", Avaada: "energy", "Tata Power": "energy", Agnikul: "aerospace", Skyroot: "aerospace", Pixxel: "aerospace",
  Ideaforge: "aerospace", "Garuda Aerospace": "aerospace", Detect: "saas", Locus: "logistics", "Locus.sh": "logistics", FarEye: "logistics", Rivigo: "logistics",
  Ecom_Express: "logistics", "Ecom Express": "logistics", Dunzo2: "consumer", Swiggy2: "consumer", Magicpin: "consumer", Nearbuy: "consumer",
  Rebel: "consumer", "Rebel Foods": "consumer", EatSure: "consumer", Chaayos: "food", "Third Wave Coffee": "food", Wow: "food", "Wow! Momo": "food",
  Country_Delight: "consumer", "Country Delight": "consumer", Milkbasket: "consumer", Otipy: "agritech", Arya: "agritech", AgroStar: "agritech",
  Bijak: "agritech", Jai_Kisan: "fintech", "Jai Kisan": "fintech", Samunnati: "fintech", Unnati: "agritech", Vegrow: "agritech", Waycool: "agritech",
  InfraMarket: "b2b", "Infra.Market": "b2b", Udaan2: "b2b", IndiaMART: "b2b", Tradeindia: "b2b", Vyapar: "saas", Zoho2: "saas", Tally: "saas",
  "Tally Solutions": "saas", Marg: "saas", Busy: "saas", Refyne: "fintech", "Salary Box": "hr", SalaryBox: "hr", Keka: "hr", greytHR: "hr",
  "Greytip": "hr", Zimyo: "hr", HROne: "hr", Springworks: "hr", Instahyre: "hr", Hirect: "hr", Cutshort: "hr", Unstop: "hr", Internshala: "hr",
  Taggd: "hr", Quess: "staffing", "Quess Corp": "staffing", TeamLease: "staffing", CIEL: "staffing", Randstad: "staffing", Adecco: "staffing",
  ManpowerGroup: "staffing", Xpheno: "staffing", "Careernet": "staffing", Vahan: "hr", "Vahan.ai": "hr", Awign: "staffing", Betterplace: "hr",
  "BetterPlace": "hr", OkayGo: "staffing", Indeed: "hr", Glassdoor: "hr", LinkedIn: "hr",
  // More global companies with India hubs (GCCs)
  Microsoft: "technology", Google: "technology", Amazon: "technology", Meta: "technology", Apple: "technology", Netflix: "media", Spotify: "media",
  Adyen: "fintech", Klarna: "fintech", Checkout: "fintech", "Checkout.com": "fintech", Nium: "fintech", Airwallex: "fintech", Rapyd: "fintech",
  Payoneer: "fintech", Remitly: "fintech", Chime: "fintech", SoFi: "fintech", Nubank: "fintech", Monzo: "fintech", Starling: "fintech",
  Kraken: "fintech", Gemini: "fintech", Binance: "fintech", OKX: "fintech", Circle: "fintech", Ripple: "fintech", Consensys: "web3", Solana: "web3",
  "Solana Foundation": "web3", Aptos: "web3", "Aptos Labs": "web3", Sui: "web3", "Mysten Labs": "web3", Near: "web3", Chainlink: "web3", Uniswap: "web3",
  Paxos2: "fintech", Tipalti: "fintech", Bill: "fintech", "Bill.com": "fintech", Navan: "travel", TripActions: "travel", Booking: "travel", Trivago: "travel",
  Zalando: "ecommerce", Shopify: "ecommerce", Etsy: "ecommerce", Wayfair: "ecommerce", Chewy: "ecommerce", Poshmark: "ecommerce", Carousell: "ecommerce",
  Shopee: "ecommerce", Sea: "ecommerce", Lazada: "ecommerce", Tokopedia: "ecommerce", Traveloka: "travel", Careem: "mobility", Talabat: "consumer",
  Deliveroo: "consumer", "Delivery Hero": "consumer", Glovo: "consumer", Bolt: "mobility", Lyft: "mobility", Lime: "mobility", Via: "mobility",
  Motive: "saas", KeepTruckin: "saas", Flexport: "logistics", project44: "logistics", FourKites: "logistics", Shippo: "logistics", Cargomatic: "logistics",
  ServiceTitan: "saas", Procore: "saas", Veeva: "saas", "Veeva Systems": "saas", Medallia: "saas", Qualtrics: "saas", SurveyMonkey: "saas", Momentive: "saas",
  Coupa: "saas", Anaplan: "saas", Workato: "saas", Celonis: "saas", UiPath: "saas", "Automation Anywhere": "saas", Pega: "saas", Appian: "saas",
  Outreach: "saas", Gong: "saas", Clari: "saas", Highspot: "saas", Seismic: "saas", Freshbooks: "saas", Xero: "saas", Intuit: "fintech",
  Sage: "saas", "Zoom": "saas", RingCentral: "saas", Vonage: "saas", Sinch: "saas", MessageBird: "saas", Bird: "saas", Plivo: "saas", Kaleyra: "saas",
  Twitch: "media", Roblox: "gaming", Unity: "gaming", "Epic Games": "gaming", Riot: "gaming", "Riot Games": "gaming", Zynga: "gaming", Supercell: "gaming",
  Moonfrog: "gaming", Kwalee: "gaming", Scopely: "gaming", Playtika: "gaming", "Electronic Arts": "gaming", Activision: "gaming",
  CrowdStrike: "security", "Palo Alto Networks": "security", SentinelOne: "security", Snyk: "security", Wiz: "security", Tenable: "security", Rapid7: "security",
  Qualys: "security", Netskope: "security", Illumio: "security", Cohesity: "saas", Commvault: "saas", Veeam: "saas", "Pure Storage": "technology",
  NetApp: "technology", Arista: "technology", "Arista Networks": "technology", Juniper: "technology", Fortinet: "security", Akamai: "technology",
  Fastly: "technology", DigitalOcean: "cloud", Linode: "cloud", Vultr: "cloud", Hetzner: "cloud", Scaleway: "cloud", Render: "cloud", Netlify: "cloud",
  Fly: "cloud", "Fly.io": "cloud", Railway: "cloud", Replit: "saas", JetBrains: "saas", Docker: "saas", "Canonical": "saas", "Red Hat": "saas", SUSE: "saas",
  Mozilla: "saas", Wikimedia: "media", Automattic: "saas", "Stack Overflow": "saas", GitHub: "saas", Atlassian2: "saas", Zendesk2: "saas", Doist: "saas",
  Buffer: "saas", Hotjar: "saas", Toggl: "saas", Remote: "hr", "Remote.com": "hr", Papaya: "hr", "Papaya Global": "hr", Multiplier: "hr", Velocity: "hr",
  Hibob: "hr", Personio: "hr", Lattice: "hr", "Culture Amp": "hr", Leapsome: "hr", BambooHR: "hr", Workable: "hr", Greenhouse: "hr", Lever: "hr",
  Ashby: "hr", SmartRecruiters: "hr", Teamtailor: "hr", Hiver: "saas", Kapture2: "saas", Sprinto: "security", Scrut: "security", "Scrut Automation": "security",
  CloudSEK: "security", Securden: "security", Seqrite: "security", Quick_Heal: "security", "Quick Heal": "security", Appknox: "security", Astra: "security",
  "Astra Security": "security", BeagleSecurity: "security", Hackerone: "security", Bugcrowd: "security", Synack: "security", Cobalt: "security",
  Mistral: "ai", "Mistral AI": "ai", "Hugging Face": "ai", HuggingFace: "ai", Perplexity: "ai", Runway: "ai", ElevenLabs: "ai", Synthesia: "ai",
  Jasper: "ai", Writer: "ai", Typeface: "ai", Adept: "ai", Character: "ai", "Character.AI": "ai", Anyscale: "ai", Modal: "ai", Replicate: "ai",
  Pinecone: "ai", Weaviate: "ai", Qdrant: "ai", Chroma: "ai", LangChain: "ai", LlamaIndex: "ai", Weights: "ai", "Weights & Biases": "ai",
  Labelbox: "ai", Snorkel: "ai", "Snorkel AI": "ai", Dataiku: "data", DataRobot: "data", H2O: "ai", "H2O.ai": "ai", Domino: "data", Alteryx: "data",
  Tableau: "data", Looker: "data", Sisense: "data", Qlik: "data", MicroStrategy: "data", Starburst: "data", Dremio: "data", Imply: "data", Clickhouse: "data",
  ClickHouse: "data", Timescale: "data", InfluxData: "data", Neo4j: "data", DataStax: "data", Aerospike: "data", MariaDB: "data", PlanetScale: "data",
  Neon: "data", Prisma: "saas", Hasura2: "saas", Apollo: "saas", "Apollo GraphQL": "saas", Postman2: "saas", Kong2: "saas", Tyk: "saas", Mulesoft: "saas",
  Boomi: "saas", SnapLogic: "saas", Informatica: "data", Talend: "data", Collibra: "data", Alation: "data", "Monte Carlo": "data", Hightouch: "data",
  Census: "data", Segment: "data", RudderStack: "data", mParticle: "data", Braze: "saas", Iterable: "saas", Klaviyo: "saas", Attentive: "saas",
  Sprout: "saas", "Sprout Social": "saas", Hootsuite: "saas", Later: "saas", Canva2: "saas", Picsart: "saas", VSCO: "media", Grammarly: "saas",
  Duolingo: "edtech", Coursera: "edtech", Udemy: "edtech", edX: "edtech", "2U": "edtech", Chegg: "edtech", Quizlet: "edtech", Brainly: "edtech",
  Kahoot: "edtech", Newsela: "edtech", Nearpod: "edtech", Instructure: "edtech", PowerSchool: "edtech", Anthology: "edtech", Ellucian: "edtech",
};

/** Exact boards for systems whose ids can't be guessed from a name. */
export const EXACT: Array<{ name: string; ats: "workday" | "oracle" | "smartrecruiters"; board: string; industry: string }> = [
  { name: "NVIDIA", ats: "workday", board: "nvidia|wd5|NVIDIAExternalCareerSite", industry: "semiconductors" },
  { name: "Walmart Global Tech", ats: "workday", board: "walmart|wd5|WalmartExternal", industry: "retail" },
  { name: "Salesforce", ats: "workday", board: "salesforce|wd12|External_Career_Site", industry: "saas" },
  { name: "Adobe", ats: "workday", board: "adobe|wd5|external_experienced", industry: "saas" },
  { name: "Intel", ats: "workday", board: "intel|wd1|External", industry: "semiconductors" },
  { name: "Mastercard", ats: "workday", board: "mastercard|wd1|CorporateCareers", industry: "fintech" },
  { name: "PwC", ats: "workday", board: "pwc|wd3|Global_Experienced_Careers", industry: "consulting" },
  { name: "Cisco", ats: "workday", board: "cisco|wd5|Cisco_Careers", industry: "technology" },
  { name: "HP", ats: "workday", board: "hp|wd5|ExternalCareerSite", industry: "technology" },
  { name: "Dell Technologies", ats: "workday", board: "dell|wd1|External", industry: "technology" },
  { name: "Target", ats: "workday", board: "target|wd5|targetcareers", industry: "retail" },
  { name: "Accenture", ats: "workday", board: "accenture|wd103|AccentureCareers", industry: "it_services" },
  { name: "Baker Hughes", ats: "workday", board: "bakerhughes|wd5|BakerHughes", industry: "energy" },
  { name: "Philips", ats: "workday", board: "philips|wd3|jobs-and-careers", industry: "healthcare" },
  { name: "Unilever", ats: "workday", board: "unilever|wd3|Unilever_Experienced_Professionals", industry: "fmcg" },
  { name: "AstraZeneca", ats: "workday", board: "astrazeneca|wd3|Careers", industry: "pharma" },
  { name: "GSK", ats: "workday", board: "gsk|wd5|GSKCareers", industry: "pharma" },
  { name: "HSBC", ats: "workday", board: "hsbc|wd3|external", industry: "banking" },
  { name: "Deutsche Bank", ats: "workday", board: "db|wd3|DBWebSite", industry: "banking" },
  { name: "Ciena", ats: "workday", board: "ciena|wd5|Careers", industry: "technology" },
  { name: "Motorola Solutions", ats: "workday", board: "motorolasolutions|wd5|Careers", industry: "technology" },
  { name: "Analog Devices", ats: "workday", board: "analogdevices|wd1|External", industry: "semiconductors" },
  { name: "NXP Semiconductors", ats: "workday", board: "nxp|wd3|careers", industry: "semiconductors" },
  { name: "Applied Materials", ats: "workday", board: "amat|wd1|External", industry: "semiconductors" },
  { name: "KLA", ats: "workday", board: "kla|wd1|Search", industry: "semiconductors" },
  { name: "Micron", ats: "workday", board: "micron|wd1|External", industry: "semiconductors" },
  { name: "Workday", ats: "workday", board: "workday|wd5|Workday", industry: "saas" },
  { name: "Sanofi", ats: "workday", board: "sanofi|wd3|SanofiCareers", industry: "pharma" },
  { name: "Novartis", ats: "workday", board: "novartis|wd3|Novartis_Careers", industry: "pharma" },
  { name: "Pfizer", ats: "workday", board: "pfizer|wd1|PfizerCareers", industry: "pharma" },
  { name: "Takeda", ats: "workday", board: "takeda|wd3|External", industry: "pharma" },
  { name: "Shell", ats: "workday", board: "shell|wd3|ShellCareers", industry: "energy" },
  { name: "3M", ats: "workday", board: "3m|wd1|Search", industry: "manufacturing" },
  { name: "Caterpillar", ats: "workday", board: "caterpillar|wd5|CaterpillarCareers", industry: "manufacturing" },
  { name: "Boeing", ats: "workday", board: "boeing|wd1|EXTERNAL_CAREERS", industry: "aerospace" },
  { name: "General Motors", ats: "workday", board: "gm|wd5|Careers_GM", industry: "automotive" },
  { name: "FIS", ats: "workday", board: "fis|wd5|SearchJobs", industry: "fintech" },
  { name: "Equifax", ats: "workday", board: "equifax|wd5|External", industry: "fintech" },
  { name: "Thomson Reuters", ats: "workday", board: "thomsonreuters|wd5|External_Career_Site", industry: "media" },
  { name: "Broadridge", ats: "workday", board: "broadridge|wd5|Careers", industry: "fintech" },
  { name: "SS&C Technologies", ats: "workday", board: "ssctech|wd5|SSCTechnologies", industry: "fintech" },
  { name: "Zebra Technologies", ats: "workday", board: "zebra|wd1|Zebra_Careers", industry: "technology" },
  { name: "Mondelez", ats: "workday", board: "mdlz|wd3|External", industry: "fmcg" },
  { name: "Kenvue", ats: "workday", board: "kenvue|wd5|KenvueCareers", industry: "fmcg" },
  { name: "Visa", ats: "workday", board: "visa|wd5|Visa_Careers", industry: "fintech" },
  { name: "Autodesk", ats: "workday", board: "autodesk|wd1|Ext", industry: "saas" },
  { name: "PayPal", ats: "workday", board: "paypal|wd1|jobs", industry: "fintech" },
  { name: "eBay", ats: "workday", board: "ebay|wd5|apply", industry: "ecommerce" },
  { name: "Nike", ats: "workday", board: "nike|wd1|nke", industry: "retail" },
  { name: "Lowe's", ats: "workday", board: "lowes|wd5|LWS_External_CS", industry: "retail" },
  { name: "Siemens Healthineers", ats: "workday", board: "healthineers|wd3|SHSJB", industry: "healthcare" },
  { name: "Samsung", ats: "workday", board: "sec|wd3|Samsung_Careers", industry: "technology" },
  { name: "Qualcomm", ats: "workday", board: "qualcomm|wd5|External", industry: "semiconductors" },
  { name: "AMD", ats: "workday", board: "amd|wd1|External", industry: "semiconductors" },
  { name: "Marvell", ats: "workday", board: "marvell|wd1|MarvellCareers", industry: "semiconductors" },
  { name: "Synopsys", ats: "workday", board: "synopsys|wd1|Careers", industry: "semiconductors" },
  { name: "Cadence", ats: "workday", board: "cadence|wd1|External_Careers", industry: "semiconductors" },
  { name: "Texas Instruments", ats: "workday", board: "ti|wd1|TI", industry: "semiconductors" },
  { name: "Western Digital", ats: "workday", board: "wdc|wd1|WD", industry: "technology" },
  { name: "Maersk", ats: "workday", board: "maersk|wd3|Maersk_Careers", industry: "logistics" },
  { name: "Standard Chartered", ats: "workday", board: "sc|wd3|Careers", industry: "banking" },
  { name: "Barclays", ats: "workday", board: "barclays|wd3|External_Career_Site_Barclays", industry: "banking" },
  { name: "Morgan Stanley", ats: "workday", board: "ms|wd5|External", industry: "banking" },
  { name: "BlackRock", ats: "workday", board: "blackrock|wd1|BlackRock_Professional", industry: "finance" },
  { name: "State Street", ats: "workday", board: "statestreet|wd1|Global", industry: "banking" },
  { name: "American Express", ats: "workday", board: "aexp|wd5|External", industry: "fintech" },
  { name: "Capgemini", ats: "workday", board: "capgemini|wd3|CapgeminiCareers", industry: "it_services" },
  { name: "JPMorgan Chase", ats: "oracle", board: "jpmc.fa.oraclecloud.com|CX_1001", industry: "banking" },
  { name: "Oracle", ats: "oracle", board: "eeho.fa.us2.oraclecloud.com|CX_45001", industry: "technology" },
  { name: "Bosch", ats: "smartrecruiters", board: "BoschGroup", industry: "manufacturing" },
  { name: "Experian", ats: "smartrecruiters", board: "Experian", industry: "fintech" },
  { name: "Freshworks", ats: "smartrecruiters", board: "Freshworks", industry: "saas" },
  { name: "ServiceNow", ats: "smartrecruiters", board: "ServiceNow", industry: "saas" },
  { name: "Visa (SR)", ats: "smartrecruiters", board: "Visa", industry: "fintech" },
  { name: "Western Union", ats: "smartrecruiters", board: "WesternUnion", industry: "fintech" },
  { name: "Ubisoft", ats: "smartrecruiters", board: "Ubisoft2", industry: "gaming" },
  { name: "Publicis Groupe", ats: "smartrecruiters", board: "PublicisGroupe", industry: "media" },
  { name: "Equinix", ats: "smartrecruiters", board: "Equinix", industry: "technology" },
  { name: "IKEA", ats: "smartrecruiters", board: "IKEA", industry: "retail" },
  { name: "Sanofi (SR)", ats: "smartrecruiters", board: "Sanofi", industry: "pharma" },
  { name: "Wipro", ats: "smartrecruiters", board: "Wipro", industry: "it_services" },
  { name: "Infosys", ats: "smartrecruiters", board: "Infosys", industry: "it_services" },
  { name: "LTIMindtree", ats: "smartrecruiters", board: "LTIMindtree", industry: "it_services" },
  { name: "Tech Mahindra", ats: "smartrecruiters", board: "TechMahindra", industry: "it_services" },
  { name: "Continental", ats: "smartrecruiters", board: "Continental", industry: "automotive" },
  { name: "Skechers", ats: "smartrecruiters", board: "SkechersUSA", industry: "retail" },
  { name: "McDonald's", ats: "smartrecruiters", board: "McDonaldsCorporation", industry: "food" },
];
