// Generates src/theme-dark.css: the dark palette for the whole app, done by re-declaring colour variables under
// html[data-theme="dark"]. Every Tailwind utility reads these variables, so the app flips without touching components.
// Run: node scripts/gen-dark.mjs
import fs from "node:fs";

const theme = fs.readFileSync("node_modules/tailwindcss/theme.css", "utf8");
const tw = (name, shade) => new RegExp(`--color-${name}-${shade}:\\s*([^;]+);`).exec(theme)?.[1].trim();
const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

const decl = (obj) => Object.entries(obj).map(([k, v]) => `  ${k}: ${v};`).join("\n");

// ---- light originals (for paper areas and printing) ----
const light = { "--color-white": "#ffffff", "--color-ink": "#0a2230", "--color-canvas": "#f3f7f8" };
const dark = { "--color-white": "#0e1a26", "--color-ink": "#eef5f8", "--color-canvas": "#060c13" };

// Slate: explicit, tuned for readable text on deep navy glass.
const slateLight = {}, slateDark = {
  50: "#0b1621", 100: "#122130", 200: "#1b2f42", 300: "#2a4459", 400: "#7189a0", 500: "#93a9bb",
  600: "#b0c1ce", 700: "#c8d5de", 800: "#dde7ed", 900: "#eef4f7", 950: "#f8fbfc",
};
for (const s of SHADES) { slateLight[s] = tw("slate", s); light[`--color-slate-${s}`] = tw("slate", s); dark[`--color-slate-${s}`] = slateDark[s]; }

// Peacock blue / green: keep the mid tones (buttons, accents), lighten the text shades, darken the tints.
const brandLight = { 50: "#ecf8fb", 100: "#d3f0f6", 200: "#a7e0ec", 300: "#6cc9dd", 400: "#34abc8", 500: "#0b8db3", 600: "#0a7399", 700: "#0b5d7e", 800: "#0d4b66", 900: "#0f3d53" };
const brandDark = { 50: "#0a2431", 100: "#0d3142", 200: "#124459", 300: "#17627d", 400: "#34abc8", 500: "#1a9cc4", 600: "#0f86ad", 700: "#5ec6e0", 800: "#93dcef", 900: "#c6eff8" };
const accentLight = { 50: "#ebfbf6", 100: "#cff5e8", 200: "#a2ead4", 300: "#62d8b8", 400: "#22bf9b", 500: "#07a384", 600: "#03846d", 700: "#086a59", 800: "#0b5549", 900: "#0c463e" };
const accentDark = { 50: "#08251f", 100: "#0a332a", 200: "#0d4a3d", 300: "#0f6553", 400: "#22bf9b", 500: "#14b08f", 600: "#0f9c7f", 700: "#5ddcbc", 800: "#94ead1", 900: "#c8f5e8" };
for (const s of Object.keys(brandLight)) { light[`--color-brand-${s}`] = brandLight[s]; dark[`--color-brand-${s}`] = brandDark[s]; light[`--color-accent-${s}`] = accentLight[s]; dark[`--color-accent-${s}`] = accentDark[s]; }

// Status colours: swap the light and dark ends, keep 400-600 (used behind white text and as accents).
const swap = { 50: 950, 100: 900, 200: 800, 300: 700, 700: 300, 800: 200, 900: 100, 950: 50 };
for (const name of ["emerald", "amber", "red", "sky", "orange", "rose", "green", "yellow", "blue"]) {
  for (const s of SHADES) {
    const orig = tw(name, s);
    if (!orig) continue;
    light[`--color-${name}-${s}`] = orig;
    dark[`--color-${name}-${s}`] = tw(name, swap[s] ?? s);
  }
}

const shadowLight = {
  "--shadow-card": "0 1px 2px rgb(10 34 48 / 0.04), 0 1px 3px rgb(10 34 48 / 0.06)",
  "--shadow-lift": "0 4px 6px -1px rgb(10 34 48 / 0.06), 0 12px 24px -6px rgb(10 60 90 / 0.12)",
  "--shadow-pop": "0 24px 48px -16px rgb(10 50 70 / 0.30)",
};
const shadowDark = {
  "--shadow-card": "0 1px 0 rgb(255 255 255 / 0.04) inset, 0 1px 3px rgb(0 0 0 / 0.5)",
  "--shadow-lift": "0 1px 0 rgb(255 255 255 / 0.05) inset, 0 12px 28px -8px rgb(0 0 0 / 0.65), 0 0 0 1px rgb(80 160 200 / 0.06)",
  "--shadow-pop": "0 28px 60px -12px rgb(0 0 0 / 0.75), 0 0 0 1px rgb(80 160 200 / 0.10)",
};
Object.assign(light, shadowLight);
Object.assign(dark, shadowDark);

const css = `/* GENERATED by scripts/gen-dark.mjs. Do not edit by hand: change the script and run it again. */

/* Dark theme: colours are variables, so every utility flips at once. */
html[data-theme="dark"] {
  color-scheme: dark;
${decl(dark)}
}

/* An always-dark scope (the landing hero stage): same palette, whatever the app theme is. */
.theme-night {
  color-scheme: dark;
${decl(dark)}
  color: #c3d1da;
}

/* Areas that must stay on white paper in dark mode (resume previews) and everything when printing. */
.theme-paper {
  color-scheme: light;
${decl(light)}
  color: #1e2f3a;
}
@media print {
  html[data-theme="dark"] {
    color-scheme: light;
${decl(light)}
  }
}
`;
fs.writeFileSync("src/theme-dark.css", css);
console.log(`wrote src/theme-dark.css (${css.split("\n").length} lines)`);
